# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  # we will push the docker image to quay.io/wangzheng422/qimgs:azure-devops-demo-***
  # changed based on your own env.
  tag: "azure-devops-demo-$(Build.BuildId),azure-devops-demo-latest"
  imageRepository: "wangzheng422/qimgs"
  # remember to set up service connection, in project setting -> pipelines -> service connections
  dockerRegistryServiceConnection: "quay.io"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: Default # use self-managed agent pool
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce' # string. Required. Docker Version. Default: 17.09.0-ce.
              #releaseType: 'stable' # 'stable' | 'edge' | 'test' | 'nightly'. Release type. Default: stable.
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                $(tag)
